wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    start_time: 1651722345
    t:
      1:
      - 3
      - 55
      2:
      - 3
      - 55
      4: 3.7.10
      5: 0.12.16
      8:
      - 3
      - 5
